### PR TITLE
Fix action packaging macos

### PR DESCRIPTION
**Pull request by airvzxf**
Hi, again @TheLastProject.

Regarding the issue #471.

I am determined to make the version of Linux and macOS work in optimal conditions for the version installed as the portable one. For that reason, I've been doing experiments with the different versions of the operating systems and Python, which are basically the main differences when building the application.

Rationale: Since most of the problems in the Linux packaging actions were resolved by upgrading the Python version.

Your friend could review each of the following versions, especially paying attention to the portable ones:
- [macos-10.15-Python_3.7-Portable_0](https://github.com/airvzxf/Pext/suites/8923925925/artifacts/409220771)
- [macos-10.15-Python_3.7-Portable_1](https://github.com/airvzxf/Pext/suites/8923925925/artifacts/409220773)
- [macos-10.15-Python_3.8-Portable_0](https://github.com/airvzxf/Pext/suites/8923925925/artifacts/409220776)
- [macos-10.15-Python_3.8-Portable_1](https://github.com/airvzxf/Pext/suites/8923925925/artifacts/409220778)
- [macos-10.15-Python_3.9-Portable_0](https://github.com/airvzxf/Pext/suites/8923925925/artifacts/409220781)
- [macos-10.15-Python_3.9-Portable_1](https://github.com/airvzxf/Pext/suites/8923925925/artifacts/409220782)
- [macos-11-Python_3.7-Portable_0](https://github.com/airvzxf/Pext/suites/8923925925/artifacts/409220785)
- [macos-11-Python_3.7-Portable_1](https://github.com/airvzxf/Pext/suites/8923925925/artifacts/409220787)
- [macos-11-Python_3.8-Portable_0](https://github.com/airvzxf/Pext/suites/8923925925/artifacts/409220790)
- [macos-11-Python_3.8-Portable_1](https://github.com/airvzxf/Pext/suites/8923925925/artifacts/409220792)
- [macos-11-Python_3.9-Portable_0](https://github.com/airvzxf/Pext/suites/8923925925/artifacts/409220795)
- [macos-11-Python_3.9-Portable_1](https://github.com/airvzxf/Pext/suites/8923925925/artifacts/409220798)
- [macos-12-Python_3.7-Portable_0](https://github.com/airvzxf/Pext/suites/8923925925/artifacts/409220800)
- [macos-12-Python_3.7-Portable_1](https://github.com/airvzxf/Pext/suites/8923925925/artifacts/409220801)
- [macos-12-Python_3.8-Portable_0](https://github.com/airvzxf/Pext/suites/8923925925/artifacts/409220803)
- [macos-12-Python_3.8-Portable_1](https://github.com/airvzxf/Pext/suites/8923925925/artifacts/409220804)
- [macos-12-Python_3.9-Portable_0](https://github.com/airvzxf/Pext/suites/8923925925/artifacts/409220806)
- [macos-12-Python_3.9-Portable_1](https://github.com/airvzxf/Pext/suites/8923925925/artifacts/409220807)

Reference of the action packing:
- https://github.com/airvzxf/Pext/actions/runs/3310982184

Summary of changes:
- Permanent.
  - Packing action.
    - Added matrix for different operative systems and Python versions.
    - In Linux job use one script for all the process (install dependencies, run tests and builds).
  - Renamed `ci/bootstrap-container.sh` to `ci/build-linux.sh`.
  - Renamed `ci/build-appimage.sh` to `ci/build-app-image.sh`.
  - The script `ci/build-app-image.sh` was improved. 
  - The script `ci/build-app-image.sh` was improved.
- Temporary changes and they will be restored to this original version.
  - The action codeQL analysis was commented.
  - In the main Python script was added the `print` when it is checking if it is a portable version.
  - In the packing action, the upload job was commented.
  - Added `echo`’s for debugging in `ci/build-app-image.sh`.

### CODE REVIEW

**Comment by TheLastProject** [comment]
I'm afraid that from testing all 9 `Portable_1` versions crash on launch in the same way. I've also been told "some of the _0's also crash now, didn't test all of them, but the _0 from the previous PR worked okay"

**Comment by airvzxf** [comment]
> I'm afraid that from testing all 9 Portable_1 versions crash on launch in the same way. I've also been told "some of the _0's also crash now, didn't test all of them, but the _0 from the previous PR worked okay"

I accidentally deleted the branch, and I didn't recover the changes. I remember they were easy, but allow me to explain:

- These improvements are for macOS and/or Linux.
- Do not be afraid. I am doing the best I can, and I have good natural skills. These include being a perfectionist, optimizing, reducing processes and facilitating the user experience as much as possible without sacrificing performance.
- This new version is huge better because it provides the opportunity to add different builds for different operating systems and versions of Python without changes or minimal changes.
- I made changes to avoid the “hacks” about import `ppa` (Personal Package Archive). Presently, it takes the original versions of Python and pip from the OS.
- vEnv is not taking from the packages, for example `python3.9-venv`. It is taking from `pip` based on the version of installed Python (`python3 -m pip install --user virtualenv`).
- QT5 is not installed from outside packages. It was taken from the operative system.
- Updated used actions to the new versions, for example: `actions/setup-python@v4`, `actions/upload-artifact@v3`.

This is the final version, could you check it the AppImage and macOS versions are working? In case the macOS is not working, I can change the OS from macos-12 to macos-11 or macos-10.15.

Builds https://github.com/airvzxf/Pext/actions/runs/3317163069:
- [macos-12-Python_3.9-Portable_0](https://github.com/airvzxf/Pext/suites/8940142604/artifacts/410264172)
- [ubuntu-20.04-Python_3.9-Portable_0](https://github.com/airvzxf/Pext/suites/8940142604/artifacts/410264173)
- [ubuntu-20.04-Python_3.9-Portable_1](https://github.com/airvzxf/Pext/suites/8940142604/artifacts/410264174)

File: ci/build-linux.sh [hunk 1]
```diff
@@ -0,0 +1,47 @@
...
+  sudo apt-get install -y qt5-default qt5-qmake qtbase5-dev-tools qttools5-dev-tools
+fi
+
+# Create the Python vEnv
+python3 -m venv pext-env
+source pext-env/bin/activate
+python3 -m pip install --upgrade pip
+
+# Install Tox Travis
+python3 -m pip install tox-travis
```
Comment (TheLastProject) [inline ci/build-linux.sh:31]: I think we can just use regular tox nowadays actually, as we moved from Travis to GitHub Actions quite some time ago.

**Review by TheLastProject — CHANGES_REQUESTED** [review]
I do generally like the new layouts, but do have some concerns/issues

File: .github/workflows/main.yml [hunk 2]
```diff
@@ -16,35 +16,32 @@ jobs:
     strategy:
       matrix:
         PEXT_BUILD_PORTABLE: [0, 1]
-    name: "AppImage (portable: ${{ matrix.PEXT_BUILD_PORTABLE }})"
-    runs-on: ubuntu-18.04
+        # Operative systems: [ubuntu-18.04, ubuntu-20.04, ubuntu-22.04]
+        # The Ubuntu version 22.04 has problems with Linux script to deploy plugin conda.
+        OPERATIVE_SYSTEM: [ubuntu-latest]
```
[the remark this answers is not in the document]
Comment (airvzxf) [reply .github/workflows/main.yml:21]: I agree. I don't have experience with AppImage, also I didn't understand how to use this build files in my Linux to use the app. You are the expert here. Is it fine to change the version to ubuntu-18.04?

[the remark this answers is not in the document]
Comment (TheLastProject) [reply .github/workflows/main.yml:21]: Yeah, 18.04 is the oldest still supported Ubuntu release so that seems like the best option (that way security patches do make it into the AppImage)

File: .github/workflows/main.yml [hunk 3]
```diff
@@ -16,35 +16,32 @@ jobs:
...
+        # Python versions: ["3.6", "3.7", "3.8", "3.9", "3.10"]
+        # The Python versions 3.6 has problems with QT.
+        # The Python versions 3.10 has problems with Tox Travis.
```
[the remark this answers is not in the document]
Comment (airvzxf) [reply .github/workflows/main.yml:24]: With Python 3.6. Using this version cannot get the QT version assigned in the `requirements.txt` (`pyqt5==5.15.7`) because Python / Pip is out of the scope of the last version of QT.

https://github.com/airvzxf/Pext/actions/runs/3315468471/jobs/5476098003

```text
ERROR: Could not find a version that satisfies the requirement pyqt5==5.15.7 (from versions: 5.7.1, 5.8, 5.8.1.1, 5.8.2, 5.9, 5.9.1, 5.9.2, 5.10, 5.10.1, 5.11.2, 5.11.3, 5.12, 5.12.1, 5.12.2, 5.12.3, 5.13.0, 5.13.1, 5.13.2, 5.14.0, 5.14.1, 5.14.2, 5.15.0, 5.15.1, 5.15.2, 5.15.3, 5.15.4, 5.15.5, 5.15.6)
ERROR: No matching distribution found for pyqt5==5.15.7
Error: Process completed with exit code 1.
```

---

For Python 3.10. I researched solutions, but there are no solutions, Tox Travis needs to change a validation about the Python version and import or not the collections. Furthermore, I added an issue in the official repository [Not working with Python 3.10 in Linux](https://github.com/tox-dev/tox-travis/issues/158).

[StackOverflow ➟ Python - can't import Set from sets ("no module named sets")](https://stackoverflow.com/questions/12028204/python-cant-import-set-from-sets-no-module-named-sets)

https://github.com/airvzxf/Pext/actions/runs/3315468471/jobs/5476098553

```text
Traceback (most recent call last):
  File "/home/runner/work/Pext/Pext/.tox/py310/bin/pep257", line 5, in <module>
    from pep257 import main
  File "/home/runner/work/Pext/Pext/.tox/py310/lib/python3.10/site-packages/pep257.py", line 24, in <module>
    from collections import defaultdict, namedtuple, Set
ImportError: cannot import name 'Set' from 'collections' (/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/collections/__init__.py)
ERROR: InvocationError for command /home/runner/work/Pext/Pext/.tox/py310/bin/pep257 pext/ pext_dev/__main__.py (exited with code 1)
___________________________________ summary ____________________________________
ERROR:   py310: commands failed
Error: Process completed with exit code 1.
```

[the remark this answers is not in the document]
Comment (TheLastProject) [reply .github/workflows/main.yml:24]: Hmm, looking at that error it actually seems to be that pep257 is giving trouble.

I looked pep257 up on PyPI and noticed it hasn't been updated since 2015: https://pypi.org/project/pep257/#history

However, if you go to https://pypi.org/project/pep257/#description and click "[Read the full documentation here](http://pep257.readthedocs.org/)." you see "pydocstyle is a rename and continuation of pep257, a project created by Vladimir Keleshev."

So maybe we can just replace `pep257` with `pydocstyle` in the tox.ini to get a more up-to-date pep257 with Python 3.10 support?

File: .github/workflows/main.yml (hunk 2 above)
[the remark this answers is not in the document]
Comment (airvzxf) [reply .github/workflows/main.yml:21]: Only be aware if the GitHub action is failing because Ubuntu 18.04 is deprecated on 12/1/22. If it fails you need to move to the latest (stable version) in GitHub which is the 20.04.

[GitHub Actions ➟ Supported runners and hardware resources](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources)

[GitHub Actions: The Ubuntu 18.04 Actions runner image is being deprecated and will be removed by 12/1/22](https://github.blog/changelog/2022-08-09-github-actions-the-ubuntu-18-04-actions-runner-image-is-being-deprecated-and-will-be-removed-by-12-1-22/)

```text
Ubuntu 18.04 [deprecated]
ubuntu-18.04
Migrate to ubuntu-20.04 or ubuntu-22.04. For more information, see this GitHub blog post.
```

Same for macOS 10.15:

[GitHub Actions The macOS 10.15 Actions runner image is being deprecated and will be removed by 8/30/22](https://github.blog/changelog/2022-07-20-github-actions-the-macos-10-15-actions-runner-image-is-being-deprecated-and-will-be-removed-by-8-30-22/)

```text
macOS Catalina 10.15 [deprecated]
macos-10.15
Migrate to macOS-11 or macOS-12. For more information, see this GitHub blog post.
```

[the remark this answers is not in the document]
Comment (TheLastProject) [reply .github/workflows/main.yml:21]: Oh wow, what an annoying thing for GitHub to do, but I kinda get it.

For macOS I don't think we need to build on an older version, AppImage is a Linux specific thing. I assume that building on the latest macOS should just work for all (hopefully)

File: ci/build-linux.sh (hunk 1 above)
Comment (airvzxf) [reply ci/build-linux.sh]: Solved in commit b738120.

GitHub's actions are green and the artifacts in place: https://github.com/airvzxf/Pext/actions/runs/3324391960.

Pext action: https://github.com/Pext/Pext/actions/runs/3324392289

File: ci/build-macos.sh [hunk 4]
```diff
@@ -0,0 +1,17 @@
+#! /bin/bash
+
+PYTHON_VERSION="${1}"
+
+# Install Tox Travis
+pip3 install tox-travis
```
[the remark this answers is not in the document]
Comment (airvzxf) [reply ci/build-macos.sh]: Solved in commit b738120.

GitHub's actions are green and the artifacts in place: https://github.com/airvzxf/Pext/actions/runs/3324391960.

Pext action: https://github.com/Pext/Pext/actions/runs/3324392289

File: .github/workflows/main.yml (hunk 2 above)
[the remark this answers is not in the document]
Comment (airvzxf) [reply .github/workflows/main.yml]: Solved in the commit: 9391904.

All the GitHub actions are green and the artifacts in place:
- https://github.com/airvzxf/Pext/actions/runs/3324538000
- https://github.com/Pext/Pext/actions/runs/3324538211

File: .github/workflows/main.yml (hunk 3 above)
[the remark this answers is not in the document]
Comment (airvzxf) [reply .github/workflows/main.yml:24]: I tried to make the change, but it crashes the tests. Could we add a new issue or fix on another branch or pull-request, please? It will help me to have more pull request for the Hacktoberfest, and also is little out of the scope about fix the AppImage and macOS build.

Logs: https://github.com/airvzxf/Pext/actions/runs/3324888315/jobs/5497014678

```text
py39 run-test: commands[3] | pydocstyle pext/ pext_dev/__main__.py
[7134] /home/runner/work/Pext/Pext$ /home/runner/work/Pext/Pext/.tox/py39/bin/pydocstyle pext/ pext_dev/__main__.py
pext/ui_qt5.py:1560 in public method `on_press`:
        D401: First line should be in imperative mood (perhaps 'Execute', not 'Executed')
pext/ui_qt5.py:1575 in public method `on_release`:
        D401: First line should be in imperative mood (perhaps 'Execute', not 'Executed')
ERROR: InvocationError for command /home/runner/work/Pext/Pext/.tox/py39/bin/pydocstyle pext/ pext_dev/__main__.py (exited with code 1)
___________________________________ summary ____________________________________
ERROR:   py39: commands failed
```

[the remark this answers is not in the document]
Comment (TheLastProject) [reply .github/workflows/main.yml:24]: Ah, `pydocstyle` added new rules that the code should abide by. I guess we can just put `|| true` at the end of the texts and a big `FIXME: Fix tests` above it, at least for now yeah

[the remark this answers is not in the document]
Comment (TheLastProject) [reply .github/workflows/main.yml:24]: Oh, I see now you already went back to pep257. That works too for now then.

**Comment by TheLastProject** [comment]
The AppImage runs okay, but is missing translations (but this could have been broken before, and at least it builds now, so whatever).

The macOS build seems to work although the tester claims it's impossible to install any module in it ("it just loops"). But hey, at least it builds and that's still an improvement.

So I'll just hit merge because it does improve Pext's current situation and is helping drag it out of its abandoned state
